### PR TITLE
development: add docker docs

### PR DESCRIPTION
**Pull request by aerickson**
Docker seems like the best way to build currently, but it was hard to get started with it. 

Add example docker commands and document tweaks that CI use to make addon builds work.

### CODE REVIEW

**Comment by CvH** [comment]
@heitbaum  ^^^^^^^^^^

**Comment by heitbaum** [comment]
@aerickson - if you could please squash you commits. Happy to approve and merge.

**Comment by aerickson** [comment]
Rebased. Thank you. :)

**Comment by heitbaum** [comment]
Thanks for the contribution - merged.

**Pull request merged**
